name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  publish-abstractions:
    permissions:
      contents: read
      id-token: write
    environment:
      name: production_feeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.ref }}
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '3.4'
          bundler-cache: true
          bundler: 'latest'
          cache-version: 1
          working-directory: components/abstractions
      - name: Run tests
        working-directory: components/abstractions
        run: bundle exec rake
      - name: Configure RubyGems trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@dc5a8d8553e6ee01fc26761a49e99e733d17954a # v2.1.0
      - name: Publish microsoft_kiota_abstractions to RubyGems
        working-directory: components/abstractions
        run: |
          gem build *.gemspec
          gem push *.gem

  publish-downstream:
    needs: publish-abstractions
    permissions:
      contents: read
      id-token: write
    environment:
      name: production_feeds
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
          - { name: serialization-json, dir: components/serialization/json }
          - { name: http, dir: components/http }
          - { name: authentication-oauth, dir: components/authentication/oauth }
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.ref }}
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '3.4'
          bundler-cache: true
          bundler: 'latest'
          cache-version: 1
          working-directory: ${{ matrix.component.dir }}
      - name: Run tests
        working-directory: ${{ matrix.component.dir }}
        run: bundle exec rake
      - name: Configure RubyGems trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@dc5a8d8553e6ee01fc26761a49e99e733d17954a # v2.1.0
      - name: Publish ${{ matrix.component.name }} to RubyGems
        working-directory: ${{ matrix.component.dir }}
        run: |
          gem build *.gemspec
          gem push *.gem
